config/routes.rb
MongodbTest::Application.routes.draw do

  resources :jobs
  
  resources :employers do
    resources :jobs, :only => :index
  end
  
  root :to => "employers#new"

end

app/models/employer.rb
class Employer
  include MongoMapper::Document         

  key :name, :presence => true, :length => { :minimum => 3 }
  # add Google map?
  key :location, String
  key :phone_number, String
  key :link, String
  key :email, String
  # add picture of the restaurant?

# Validations :::::::::::::::::::::::::::::::::::::::::::::::::::::
  # Great website for validations:
  # http://api.rubyonrails.org/classes/ActiveModel/Validations/HelperMethods.html
  # http://guides.rubyonrails.org/v3.2.13/active_record_validations_callbacks.html#displaying-validation-errors-in-the-view
 validates_presence_of :name

 validates_uniqueness_of :name


# Assocations :::::::::::::::::::::::::::::::::::::::::::::::::::::
 many :jobs
end

app/models/job.rb
class Job
  include MongoMapper::Document         

  #keys
  key :title
  key :job_description, String
  #look at money gem for decimals not integer
  key :pay, Integer
  # If we just want to validate numeric:
  # key :age, Integer, :numeric => true
  key :age, Integer
  key :required_experience, String
  key :hours_needed, String
  key :benefits, String
  key :employer_id, ObjectId
  
# Validations :::::::::::::::::::::::::::::::::::::::::::::::::::::
 validates_presence_of :title
  validates_presence_of :age
  # The code below checks to see if the job title already exists for the employer.
  #  We can add the same job title for 2 different employers.
 validates_uniqueness_of :title, :scope => :employer_id
  validates_numericality_of :age, greater_than: 15
# Assocations :::::::::::::::::::::::::::::::::::::::::::::::::::::
 belongs_to :employer

# Callbacks ::::::::::::::::::::::::::::::::::::::::::::::::::::::: 
# before_create :your_model_method
# after_create :your_model_method
# before_update :your_model_method 

# Attribute options extras ::::::::::::::::::::::::::::::::::::::::
# attr_accessible :first_name, :last_name, :email

# Validations
# key :name, :required =>  true      

# Defaults
# key :done, :default => false

# Typecast
# key :user_ids, Array, :typecast => 'ObjectId'     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_filter :fetch_employer_from_url, :only => [:edit, :update]
  
  def new
    @employer = flash[:employer] || Employer.new
  end
  
  def edit
    @employer = flash[:employer] || @employer
  end
  
  def index
    @employers = Employer.all
  end
  
  def create
    @employer = Employer.new(params[:employer])
    
    if @employer.save
      redirect_to employers_url
    else
      flash[:employer] = @employer
      redirect_to new_employer_url
    end
  end
  
  def update
    if @employer.update_attributes(params[:employer])
      redirect_to employers_url
    else
      flash[:employer] = @employer
      redirect_to edit_employer_url(@employer)
    end
  end
  
  private
    
  def fetch_employer_from_url
    @employer = Employer.find(params[:id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :need_employers
  before_filter :fetch_job_from_url, :only => [:edit, :update, :destroy]
  
  def new
    @job = flash[:job] || Job.new
  end
  
  def edit
    @job = flash[:job] || @job
  end
  
  def index
    @jobs = Job.all
  end
  
  def create
    @job = Job.new(params[:job])
    
    if @job.save
      redirect_to jobs_url
    else
      flash[:job] = @job
      redirect_to new_job_url
    end
  end
  
  def destroy
    @job.destroy
    redirect_to jobs_url
  end
  
  def update
    if @job.update_attributes(params[:job])
      redirect_to jobs_url
    else
      flash[:job] = @job
      redirect_to edit_job_url(@job)
    end
  end
  
  private
  def need_employers
    if Employer.count == 0
      flash[:notice] = "Add some employers first"
      redirect_to new_employer_url
    end
  end
    
  def fetch_job_from_url
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/employers/_form.html.erb
<!-- The code below will also work instead of f.error_messages -->
<!--<%=error_messages_for :employer%>    -->
<%=form_for @employer do |f|%>
    <%= f.error_messages %>
   <p>Name: <%=f.text_field :name%></p>
    <p>Location: <%=f.text_field :location%></p>
    <p>Phone Number: <%=f.text_field :phone_number%></p>
    <p>Website: <%=f.text_field :link%></p>
    <p>Email: <%=f.email_field :email%></p>
    <p><%=f.submit :Save%></p>
<%end%>

app/views/employers/edit.html.erb
<h2>Edit an employer</h2>
<%=render :partial => "form"%>

app/views/employers/index.html.erb
<h2>All employers</h2>

<ul>
<%@employers.each do |employer|%>
  <li><%=employer.name%> (<%=pluralize(employer.jobs.count,"job")%>) | <%=link_to "Edit", edit_employer_url(employer)%></li>
<%end%>
</ul>

<%=link_to "Add a new employer", new_employer_url%>

app/views/employers/new.html.erb
<h2>Add an employer</h2>
<%=render :partial => "form"%>

app/views/jobs/_form.html.erb
<%=form_for @job do |f|%>
    <%= f.error_messages %>
  <p>Title: <%=f.text_field :title%></p>  
  <p>Employer: <%=f.select :employer_id, Employer.all.collect{|a| [a.name,a.id]}%></p>
    <!--   http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html
    text_field, telephone_field, url_field
    -->
    <p>Job Description: <%=f.text_field :job_description%></p>
    <p>Pay: <%=f.number_field :pay%></p>
      <p>Minimum Age: <%=f.number_field :age%></p>
    <p>Required Experience: <%=f.text_field :required_experience%></p>
    <p>Hours Needed: <%=f.text_field :hours_needed%></p>
    <p>Benefits: <%=f.text_field :benefits%></p>
    <p><%=f.submit :Save%></p>
<%end%>

app/views/jobs/edit.html.erb
<h2>Edit a job</h2>
<%=render :partial => "form"%>

app/views/jobs/index.html.erb
<h2>All jobs</h2>

<ul>
<%@jobs.each do |job|%>
  <li><%=job.title%> (<%=job.employer.name%>) | <%=link_to "Edit", edit_job_url(job)%> | <%=link_to "Delete", job_url(job), :method => :delete%></li>
<%end%>
</ul>

<%=link_to "Add a new job", new_job_url%>

app/views/jobs/new.html.erb
<h2>Create a job</h2>
<%=render :partial => "form"%>

app/views/jobs/show.html.erb
<h2>Deleted the job</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StephanieMongoDBJobPost</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "rails" %>
  <!--The following line allows the job delete to work for the link_to command.
  I could also use button_to to get the delete to work without this line
  See: http://stackoverflow.com/questions/4342083/rails-3-link-to-method-delete-not-working-->
    <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
  <h1>Stephanie MongoDB Job Post</h1>
  <p>Menu: <%=link_to "Manage Employers", employers_url%> | <%=link_to "Manage jobs", jobs_url%></p>
  <hr />
  <%if flash[:notice]%><div class='notice'><%=flash[:notice]%></div><%end%>
  <%= yield %>

</body>
</html>